import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {saveSelection,savePortableSelection,exportMemory,recallMemory} from './codex-local-memory/plugins/local-conversation-memory/src/storage.mjs';
import {readPortable,importDraft} from './codex-local-memory/plugins/local-conversation-memory/src/portable.mjs';
import {NamedMemoryStore,projectFor} from './dsh-local-memory/src/store.js';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'codex-dsh-interop-'));
try{
 const a=path.join(root,'Codex 项目'),b=path.join(root,'DSH 项目'),c=path.join(root,'返回 Codex');for(const dir of [a,b,c])await fs.mkdir(dir);
 const binary=path.join(a,'图像.bin');await fs.writeFile(binary,Buffer.from([0,255,5,78]));
 const text='用户原始说明与决定，不进行改写。';
 const draft={session:randomUUID(),project:a,omitted:3,messages:[{seq:1,role:'user',text}],points:Array.from({length:250},(_,i)=>({id:`p${i}`,text:`原始要点 ${i}`,category:'fact',source:{seq:1,role:'user'}})),resources:[{id:'a',name:'图像.bin',path:binary}]};
 const saved=await saveSelection(path.join(root,'codex-store'),draft,{name:'跨端往返',confirmed:true,pointIds:draft.points.map(p=>p.id),resourceIds:['a']});
 const original=readPortable(saved.portablePath),store=new NamedMemoryStore({storageDir:path.join(root,'dsh-store'),autoArchive:false}),project=projectFor({id:'dsh-import',header:{cwd:b}});
 const select=d=>({name:d.name,confirmed:true,pointIds:d.points.map(p=>p.id),resourceIds:d.attachments.map((a,i)=>`portable:${i}`)});
 const imported=store.savePortableSelection(project,original,select(original));assert.equal(store.read(project).entries[0].points.length,250);
 const recalled=store.context(projectFor({id:'new-dsh-reader',header:{cwd:b}}),'原始要点');assert.equal(recalled.length,1);assert(recalled[0].points.length>0);
 const exported=store.exportPortable(project,imported.id),fromDsh=readPortable(exported.file);assert.equal(original.extraction.originalMessages,1);assert.equal(fromDsh.extraction.originalMessages,undefined);const expected=structuredClone(original);delete expected.extraction.originalMessages;assert.deepEqual(fromDsh,expected);
 const back=await savePortableSelection(path.join(root,'codex-store'),importDraft(fromDsh,{session:randomUUID(),project:c}),select(fromDsh));
 const final=await exportMemory(path.join(root,'codex-store'),c,{id:back.id,file:path.join(root,'final.memory.json')});assert.deepEqual(readPortable(final.path),expected);
 assert.equal((await recallMemory(path.join(root,'codex-store'),c,{id:back.id,session:randomUUID()})).points.length,250);
 assert.throws(()=>store.savePortableSelection(project,original,select(original)),/同名|同一/);
 const d=path.join(root,'DSH native'),e=path.join(root,'Codex receives DSH'),f=path.join(root,'DSH return');for(const dir of [d,e,f])await fs.mkdir(dir);
 const nativePoints=Array.from({length:500},(_,i)=>({id:`n${i}`,text:`DSH original fact ${i}`,category:'fact',source:{seq:1,role:'user'}}));
 const nativeDraft={id:'native-draft',points:nativePoints,resources:[{id:'bin',name:'binary.bin',kind:'path',path:binary}],omitted:0};
 const dp=projectFor({id:'native-dsh',header:{cwd:d}});
 const dsaved=await store.saveDraft(dp,nativeDraft,{draftId:nativeDraft.id,name:'Native DSH sample',pointIds:nativePoints.map(p=>p.id),resourceIds:['bin'],portable:true},null,new AbortController().signal);
 assert.equal(store.read(dp).entries[0].points.length,500);
 const dd=readPortable(dsaved.portablePath);assert.equal(dd.points.length,250);assert.equal(dd.points[0].id,'n250');assert.equal(dd.extraction.omitted,250);
 const cs=await savePortableSelection(path.join(root,'codex-store'),importDraft(dd,{session:randomUUID(),project:e}),select(dd));
 const ce=await exportMemory(path.join(root,'codex-store'),e,{id:cs.id,file:path.join(root,'dsh-via-codex.memory.json')});assert.deepEqual(readPortable(ce.path),dd);
 const fp=projectFor({id:'dsh-return',header:{cwd:f}});const di=store.savePortableSelection(fp,readPortable(ce.path),select(dd));
 assert.deepEqual(readPortable(store.exportPortable(fp,di.id).file),dd);
 console.log('PASS DSH -> Codex -> DSH: native 500 points; newest 250 exchanged and imported; omission count 250; binary bytes and identity preserved.');
 console.log('KNOWN DIFFERENCE: explicit DSH re-export drops extraction.originalMessages; content, sources, attachments and original identity remain equal.');
 console.log('PASS Codex -> DSH -> Codex: 250 verbatim points, full available sources, origin identity/date, omissions, binary attachment bytes/hash, duplicate protection, DSH/Codex native recall. No cloud/model requests.');
}finally{await fs.rm(root,{recursive:true,force:true});}
